services:
    notification_manager:
        class: "CoreExtraBundle\\Service\\NotificationManager"
        calls:
            - [setContainer, ["@service_container"] ] 
    coreextra_twig_extension:
        class: "CoreExtraBundle\\Twig\\CoreExtraExtension"
        calls:
            - [setContainer, ["@service_container"] ]
        tags:
            - { name: twig.extension }        
    